<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="P12-T165934" ignored="0" name="Default test" tests="4" failures="1" timestamp="2021-09-17T11:16:46 IST" time="205.148" errors="0">
  <testcase name="createOpportunityWithOrganizationTestCase1" time="41.127" classname="com.crm.autodesk.opportunityTest.TC_21_CreateOpportunityWithSalesStageClosedLost">
    <skipped/>
  </testcase> <!-- createOpportunityWithOrganizationTestCase1 -->
  <testcase name="createOpportunityWithOrganizationTestCase1" time="33.31" classname="com.crm.autodesk.opportunityTest.TC_21_CreateOpportunityWithSalesStageClosedLost">
    <skipped/>
  </testcase> <!-- createOpportunityWithOrganizationTestCase1 -->
  <testcase name="createOpportunityWithOrganizationTestCase1" time="25.141" classname="com.crm.autodesk.opportunityTest.TC_21_CreateOpportunityWithSalesStageClosedLost">
    <skipped/>
  </testcase> <!-- createOpportunityWithOrganizationTestCase1 -->
  <testcase name="createOpportunityWithOrganizationTestCase1" time="25.206" classname="com.crm.autodesk.opportunityTest.TC_21_CreateOpportunityWithSalesStageClosedLost">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.crm.autodesk.opportunityTest.TC_21_CreateOpportunityWithSalesStageClosedLost.createOpportunityWithOrganizationTestCase1(TC_21_CreateOpportunityWithSalesStageClosedLost.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- createOpportunityWithOrganizationTestCase1 -->
</testsuite> <!-- Default test -->
